# Generated by Django 6.0.6 on 2026-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('ME', 'Mechanical'), ('CE', 'Civil')], max_length=10)),
                ('marks', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('joined', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
            ],
            options={
                'ordering': ['roll'],
            },
        ),
    ]
