# Generated by Django 6.0.6 on 2026-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(default=75, help_text='Attendance percentage (0-100)'),
        ),
    ]
