# Generated by Django 6.0.6 on 2026-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
    ]
